# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np
# 2 - 5 elemanlı bir numpy array oluşturun
numpyArray = np.array([20,5,498,37,23])
# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
numpyArray.sort()
print(numpyArray)

[  5  20  23  37 498]


# Problem 2

In [4]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
import numpy as np
x=np.array([10,15,30,45,60])
print(x)
# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
x2=np.arange(5,15)
print(x2)
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
x3=np.arange(50,100,5)
print(x3)
# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
x4=np.zeros(10)
print(x4)
# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
x5=np.ones(10)
print(x5)
# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
x6=np.linspace(0,100,5)
print(x6)
# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
rastgeleSayı=np.random.randint(10,31,size=5)
print(rastgeleSayı)
# 8- [-1 ile 1] arasında 10 adet sayı üretin.
rastgeleSayı2=np.random.uniform(-1,1,size=10)
print(rastgeleSayı2)
# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
rastgeleSayı3=np.random.randint(10, 50, size=(3,5))
print(rastgeleSayı3)
# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(rastgeleSayı3.sum(axis=0))
print(rastgeleSayı3.sum(axis=1))
# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(rastgeleSayı3.max())
print(rastgeleSayı3.min())
print(rastgeleSayı3.mean())
# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(rastgeleSayı3.argmax())
# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
rastgeleSayı4=np.random.randint(10,20,size=8)
print(rastgeleSayı4[:3])
# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(rastgeleSayı4[::-1])
# 15- Üretilen matrisin ilk satırını seçiniz.
print(rastgeleSayı3[0])
# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(rastgeleSayı3[1,2])
# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(rastgeleSayı3[:,0])
# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(rastgeleSayı3**2)
# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
rastgeleSayı5 = np.random.randint(-50,50,size=(3,5))
print((rastgeleSayı5 > 0) & (rastgeleSayı5 % 2 ==0))

[10 15 30 45 60]
[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[  0.  25.  50.  75. 100.]
[19 28 20 16 23]
[ 0.97734969 -0.76566811  0.09467327 -0.5808407  -0.46458635  0.31852849
 -0.62414808 -0.88005439 -0.71624238  0.39213551]
[[45 25 42 11 11]
 [42 29 46 48 47]
 [41 41 21 40 28]]
[128  95 109  99  86]
[134 212 171]
48
11
34.46666666666667
8
[16 16 13]
[15 13 16 17 15 13 16 16]
[45 25 42 11 11]
46
[45 42 41]
[[2025  625 1764  121  121]
 [1764  841 2116 2304 2209]
 [1681 1681  441 1600  784]]
[[False False  True False False]
 [False False False False False]
 [False False False  True False]]
