### Numpy

- Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
- Veri analizinde kullanılır.
- Bilgisayar kurmak için pip install numpy komutu kurulabilir.
- Bilimsel hesaplamalar için kullanılır.
- Arraylar / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı işlemler yapılabilir. 
- Temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçmiştir.
- Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

### Neden Numpy?

In [8]:
# Klasik yöntem
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20]


In [9]:
# Numpy ile
import numpy as np   #Burada numpy i np olarak kısalttığımızı belirttik.
a = np.array([1,2,3,4])    #array ile liste oluşturuyoruz.
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


.reshape() fonksiyonu ile arraylerin boyutlarını değiştirebiliriz.

In [10]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape ile arraylerin boyutlarını öğrenebiliriz.

In [11]:
print(multi.shape)

(3, 3)


In [12]:
print(x.shape)

(9,)


.ndim ile arraylerin boyut sayısını öğrenebiliriz.

In [14]:
print(x.ndim)

1


In [16]:
print(multi.ndim) #2boyut diyor çünkü liste içinde liste var

2


### Birleştirme (Concatenation)
- Concatenate() fonksiyonu ile birleştirme yapabiliriz. 

In [17]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [20]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [21]:
print(np.concatenate([a,a], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


axis = 0 ise satır bazında birleştirme yapar.
axis = 1 ise sütun bazında birleştirme yapar.

### Array Ayırma (Splitting)
- .split() fonksiyonu ile array ayırma yapabiliriz.

In [22]:
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]
