### Numpy

- Numpy sayısal işlemleri hızlı yapmak için C dili ile yazılmış bir Python kütüphanesidir.
- Veri analizinde kullanılır.
- Bilgisayar kurmak için pip install numpy komutu kurulabilir.
- Bilimsel hesaplamalar için kullanılır.
- Arraylar / çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı işlemler yapılabilir. 
- Temelleri 1995 yılında atıldı. Ama nihai olarak 2005 yılında Travis Oliphant tarafından hayata geçmiştir.
- Listelere benzerdir. Fakat verimli veri saklama ve vektör işlemleri için Numpy kullanılır.

### Neden Numpy?

In [8]:
# Klasik yöntem
a = [1,2,3,4]
b = [2,3,4,5]
ab = []
for i in range(0, len(a)):
    ab.append(a[i] * b[i])
print(ab)

[2, 6, 12, 20]


In [4]:
# Numpy ile
import numpy as np   #Burada numpy i np olarak kısalttığımızı belirttik.
a = np.array([1,2,3,4])    #array ile liste oluşturuyoruz.
b = np.array([2,3,4,5])
print(a*b)

[ 2  6 12 20]


.reshape() fonksiyonu ile arraylerin boyutlarını değiştirebiliriz.

In [10]:
x = np.array([1,2,3,4,5,6,7,8,9])
multi = x.reshape(3,3)
print(multi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


.shape ile arraylerin boyutlarını öğrenebiliriz.

In [11]:
print(multi.shape)

(3, 3)


In [12]:
print(x.shape)

(9,)


.ndim ile arraylerin boyut sayısını öğrenebiliriz.

In [14]:
print(x.ndim)

1


In [16]:
print(multi.ndim) #2boyut diyor çünkü liste içinde liste var

2


### Birleştirme (Concatenation)
- Concatenate() fonksiyonu ile birleştirme yapabiliriz. 

In [17]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,8,9,10])
print(np.concatenate([x,y]))

[ 1  2  3  4  5  6  7  8  9 10]


In [18]:
z = np.array([11,12,13,14,15])
print(np.concatenate([x,y,z]))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [20]:
a = np.array([[1,2,3],[4,5,6]])
print(np.concatenate([a,a]))

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [21]:
print(np.concatenate([a,a], axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


axis = 0 ise satır bazında birleştirme yapar.
axis = 1 ise sütun bazında birleştirme yapar.

### Array Ayırma (Splitting)
- .split() fonksiyonu ile array ayırma yapabiliriz.

In [5]:
m = np.array([1,2,3,99,99,3,2,1])
print(np.split(m,[3,5]))

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]


In [6]:
a,b,c = np.split(m,[3,5])
print(a)
print(b)
print(c)

[1 2 3]
[99 99]
[3 2 1]


- vsplit() fonksiyonu ile array yatay olarak ayırma yapabiliriz. 
- hsplit() fonksiyonu ile array dikey olarak ayırma yapabiliriz.

In [8]:
n = np.arange(16).reshape(4,4) #arange 1 ile yazılan sayı arasında rastgele sayı seçilmesini sağlar.
np.vsplit(n,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [9]:
np.hsplit(n,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

##### np.arange()
- Belli bir aralıkta sayıları oluşturmak için kullanılır.
- np.arange(start, stop, step)

In [10]:
np.arange(3,12,2)

array([ 3,  5,  7,  9, 11])

##### np.zeros()
- 0'lardan oluşan bir numpy dizisi oluşturulması için kullanılır

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

##### np.ones()
- 1'lerden oluşan bir numpy dizisi oluşturulması için kullanılır.

In [13]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### np.linspace()
- Belli bir aralıkta sayıları oluşturmak için kullanılır.
- np.linspace(başlangıç,bitiş,bölünecek aralık)

In [14]:
np.linspace(0,100,5) #belli aralığı istediğim sayı kadar bölmeye yarıyor.

array([  0.,  25.,  50.,  75., 100.])

In [34]:
np.random.randint(0,10,3) #0 ile 10 arasında rastgele 3 sayı üret demek istiyoruz.

array([8, 8, 2])

In [38]:
np.random.randint(2,22,5)

array([15, 17,  6,  3, 20])

In [44]:
npArray = np.arange(50)
npMulti= npArray.reshape(5,10)
print(npMulti.sum(axis=1)) #Dikeyde toplama yapsin diye axis=1 dedik

[ 45 145 245 345 445]


### Numpy Array'in Özellikleri
- ndim : Boyut sayısı
- shape : Boyut bilgisi
- size : Toplam Eleman sayısı
- dtype : Veri tipi

In [45]:
a = np.random.randint(10,size = 10)
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

1
(10,)
10
int32


### Array Sıralama(Sorting)
- Array sıralama işlemleri yapmak için numpy kütüphanesinde yer alan sort() fonksiyonu kullanılır.

In [53]:
v = np.array([8,24,232,12,5,42,55])
print(v)
v.sort()
print(v)

[  8  24 232  12   5  42  55]
[  5   8  12  24  42  55 232]


In [54]:
m = np.random.normal(20,5,(3,3))
print(m)

[[18.80182953 22.22042045 11.51758238]
 [17.47029872 21.22137143 17.01879153]
 [18.40146348 17.63357485 23.94315612]]


In [55]:
print(np.sort(m, axis = 0))

[[17.47029872 17.63357485 11.51758238]
 [18.40146348 21.22137143 17.01879153]
 [18.80182953 22.22042045 23.94315612]]


In [56]:
print(np.sort(m, axis = 1))

[[11.51758238 18.80182953 22.22042045]
 [17.01879153 17.47029872 21.22137143]
 [17.63357485 18.40146348 23.94315612]]


### Index ile Elemanlara Erişmek
- Aynı listelerde olduğu gibi index ile elemanlara erişebiliriz.

In [74]:
a = np.random.randint(10,size = 10)
print(a[0])

3


In [77]:
print(a[-1])

9


In [78]:
a[0] = 100
print(a)

[100   1   2   7   5   4   8   6   0   9]


In [79]:
x = np.random.randint(10, size=(3,5))
print(x)

[[0 4 9 5 8]
 [3 0 8 7 3]
 [3 3 2 7 7]]


In [80]:
print(x[0,0]) #Yukardaki 0. elemanın 0. elemanını yazdırdı.

0


In [82]:
print(x[1,3])

7


In [83]:
x[1,4] = 100 #1. elemanın 4.elemanını 100 yap demiş olduk
print(x)

[[  0   4   9   5   8]
 [  3   0   8   7 100]
 [  3   3   2   7   7]]


In [85]:
x[1,4] = 3.14 #Ondalıklı sayıları tam sayı olarak ekleme yapar.
print(x)

[[0 4 9 5 8]
 [3 0 8 7 3]
 [3 3 2 7 7]]


### Slicing ile Elemanlara Erişmek (Array Alt Kümesine Erişmek)

In [86]:
a = np.arange(20,30)
print(a)

[20 21 22 23 24 25 26 27 28 29]


In [91]:
print(a[0:3])

[20 21 22]


In [95]:
print(a[:3]) #0 yazıp yazmamak bir şey değiştirmiyor

[20 21 22]


In [96]:
print(a[3:])

[23 24 25 26 27 28 29]


In [97]:
print(a[1::2]) #Anlamı 1 den başla 2 şer 2 şer git demek.

[21 23 25 27 29]


In [98]:
print(a[0::2])

[20 22 24 26 28]


In [99]:
print(a[2::2])

[22 24 26 28]


In [100]:
print(a[1::5])

[21 26]


In [101]:
b = np.random.randint(10,size=[5,5])

In [104]:
print(b)

[[4 9 7 6 7]
 [1 7 2 4 1]
 [0 3 6 6 2]
 [7 3 6 6 9]
 [6 1 0 2 5]]


In [105]:
print(b[:,0]) #,0 ın anlamı tüm satırlardaki ilk sütünü al demek oluyor

[4 1 0 7 6]


In [106]:
print(b[:,1])

[9 7 3 3 1]


In [ ]:
print(b[0,:]) #0, ün anlamı ilk satırdaki elemanı yazdırması demek oluyor

In [107]:
print(b[1,:])

[1 7 2 4 1]


In [111]:
print(b[0:2,0:3])  #Anlamı 2. satıra kadar elemanların ilk 3 sütununu yazdır demek oluyor.

[[4 9 7]
 [1 7 2]]


In [112]:
print(b[::2,::2])  #2şer2şer atlayarak elemanları veriyor.

[[4 7 7]
 [0 6 2]
 [6 0 5]]


### Alt Küme Üzerinde işlem Yapmak

In [117]:
alt_b = b[0:3,0:2]
alt_b

array([[4, 9],
       [1, 7],
       [0, 3]])

In [118]:
alt_b[0,0] = 100
alt_b[1,1] = 200
alt_b

array([[100,   9],
       [  1, 200],
       [  0,   3]])

In [119]:
print(b)

[[100   9   7   6   7]
 [  1 200   2   4   1]
 [  0   3   6   6   2]
 [  7   3   6   6   9]
 [  6   1   0   2   5]]


### Fancy Index
- Bir liste içine bu arrayden istediğiniz indislerini koyarak o indislerdeki verileri alabiliriz.

In [120]:
v = np.arange(0,30,3)
print(v)

[ 0  3  6  9 12 15 18 21 24 27]


In [121]:
yetgen = [1,3,5]
print(v[yetgen])

[ 3  9 15]


In [125]:
m = np.arange(9).reshape(3,3)
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [124]:
satir = np.array([0,1])
sutun = np.array([1,2])
print(m[satir,sutun])

[1 5]


### Koşullu Eleman İşlemleri

In [126]:
v = np.array([1,2,3,4,5])
print(v > 3)

[False False False  True  True]


In [127]:
print(v[v > 3])

[4 5]


In [128]:
print(v[v < 3])

[1 2]


In [131]:
print(v[v <= 3])

[1 2 3]


In [132]:
print(v[v >= 3])

[3 4 5]


In [133]:
print(v[v != 3])

[1 2 4 5]


In [134]:
print(v[v == 3])

[3]


### Matematiksel İşlemler

In [135]:
v = np.array([1,2,3,4,5]) 
print(v*2)  #Her birini 2 ile çarp demiş olduk

[ 2  4  6  8 10]


In [136]:
print(v * 5/10)

[0.5 1.  1.5 2.  2.5]


In [137]:
print(v**2)

[ 1  4  9 16 25]


In [ ]:
print(np.subtract(v,3)) #Her birinden 3 çıkar demek istedik

In [ ]:
print(np.add(v,2)) #Her birine 2 ekler

In [138]:
print(np.multiply(v,2)) #Her birini 2 ile çarpar

[ 2  4  6  8 10]


In [139]:
print(np.divide(v,2)) #Her birini 2 ye böler

[0.5 1.  1.5 2.  2.5]


In [140]:
print(np.power(v,2)) # Üs alma

[ 1  4  9 16 25]


In [141]:
print(np.mod(v,5)) #5 e göre mod alır

[1 2 3 4 0]


In [142]:
print(np.absolute(v)) #Mutlak değer alır

[1 2 3 4 5]


In [143]:
print(np.sin(360))

0.9589157234143065


In [144]:
np.log(10)

2.302585092994046

# Ek not 
- Print ile np. .... yazdırırsak array ifadesini yazdırmaz
- Direkt np ile yazdırırsak Array ifadesi yazdırır.

### İki Bilinmeyenli Denklem Çözümü

In [150]:
# 5*x0 + x1 = 12
# x0 * 3*x1 = 10
a = np.array([[5,1],[1,3]])
b = np.array([12,10])
x = np.linalg.solve(a,b) #2 bilinmeyenli denklem çözmemize yarar
print(x)

[1.85714286 2.71428571]
